Homework 2: css-styles
ok-technopolis-autumn-2019/Marashov-Alexander pull request #2
Opened 2019-10-15 19:57 UTC by Marashov-Alexander

2019-10-20 23:25 UTC, fromanywhere requested changes

2019-10-20 23:25 UTC, fromanywhere commented on images/arrow_down.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
А в чем идея рисовать свою иконку, когда оно есть в макете?

2019-10-20 23:25 UTC, fromanywhere commented on index.html
>  <html lang="eu">
en

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +    font-family: Roboto, serif;
лучше на body, фоллбэк там будет sans-serif (https://en.wikipedia.org/wiki/Sans-serif, https://en.wikipedia.org/wiki/Serif), сам шрифт тоже нужно не забыть подключить fonts.google.com

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +        flex: auto;
выглядит лишним

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                flex-grow: 1;
не понял, зачем кнопке flex-grow, она же не заполняет контейнер

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                font-size: 15pt;
оставьте пункты полиграфистам, живем в пикселах

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                flex-grow: 40;
я уже работах в 5 встретил эту магическую конструкцию, я всё никак не могу понять, что она означает, почему 40. Там и 1 достаточно

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +        ul {
так-то обычно такие обнуления выносят в начало файла, называется css reset https://habr.com/ru/post/45296/

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +        display: flex;
В макете очень много флексовых колонок, из-за этого везде приходится писать ширину. А на самом деле они здесь примерно нигде не нужны, блочный контекст форматирования сделает всё сам

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                    flex-grow: 3;
достаточно 1, магические числа всегда тяжелы в поддержке

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                    flex-shrink: 0;
хорошо!

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                        content: '';
Очень красиво, но очень далеко от макета

2019-10-20 23:25 UTC, fromanywhere commented on styles/styles.css
> +                }
Нужно попытаться стать ближе к макету. Крестики на ховеры-фокусы, графика правильная, размер шрифта, гарнитура, отступы, сейчас функционально, но в реальной жизни дизайнер бы не перенес такого

2019-10-22 17:03 UTC, fromanywhere requested changes

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    border: 1px transparent solid;
Сейчас из-за того, что картинки по размеру и background-position совпадают, но у .item-view__checkbox-label есть border, а у .checkbox-status-off нет, при выборе элемента круг чуть-чуть дергается по горизонтали.     background-clip: padding-box; спасёт

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +        width: 562px;
Намного проще прописать ширину один раз для .todo-app, вложенные контейнеры растянутся сами

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +    height: auto;
лишнее

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +    justify-content: center;
лишнее

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +            letter-spacing: -2.5px;
не нужен отрицательный леттерспейсинг

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                width: 517px;
лишнее

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +            display: flex;
здесь предположительно всё лишнее

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                width: 562px;
Размеры лишние

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                border-bottom: 1px lightgray solid;
цвета бы из макета

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                .item-view:hover > .item-view-delete-button {
лучше без >

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    height: 41px;
предположительно размеры не нужны

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    background-size: 20px, 20px;
здесь смешная ошибка — предполагалось, что запятой на самом деле нет, потом что картинка одна. Из-за того, что стоит запятая, браузер считает, что здесь на самом деле две картинки (типа, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds). Значение до запятой он дублирует и по горизонтали, и по вертикали. То есть на самом деле здесь сейчас написано background-size: 20px 20px, 20px 20px;

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                .item__empty_place {
что-то не то с БЭМ-нотацией, я не верю, что это модификатор

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +            justify-content: space-around;
здесь лучше space-between и padding по горизонтали

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    width: auto;
размеры лишние

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                width: 192px;
я почти уверен, что ширина не нужна

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    width: inherit;
размеры лишние, и я добавил бы padding, чтобы рамка не прилипала к тексту

2019-10-22 17:03 UTC, fromanywhere commented on styles/styles.css
> +                    position: relative;
если здесь написать absolute, input перестанет занимать место в потоке, и позиционировать всё это станет проще

2019-10-25 08:50 UTC, Marashov-Alexander commented
Попытался исправить замечания

2019-10-26 14:02 UTC, fromanywhere requested changes
Последний рывок

2019-10-26 14:02 UTC, fromanywhere commented on styles/styles.css
> +                    min-width: 0;
![image](https://user-images.githubusercontent.com/1042969/67620671-02b49680-f812-11e9-90bc-38be0518012a.png)

2019-10-26 14:02 UTC, fromanywhere commented on styles/styles.css
> +                box-shadow: inset 0 -1px 0 #E6E6E6;
Здесь возьмите, пожалуйста, бордер вместо тени, а то кнопка перекрывает на ховер 
![image](https://user-images.githubusercontent.com/1042969/67620689-32fc3500-f812-11e9-8d4d-444432d243f8.png)

2019-10-27 14:53 UTC, Marashov-Alexander commented on styles/styles.css
> +                    min-width: 0;
Добавил word-break: break-word; для переноса слов

2019-10-27 14:54 UTC, Marashov-Alexander commented on styles/styles.css
> +                box-shadow: inset 0 -1px 0 #E6E6E6;
Хорошо, сделал

2019-10-27 21:38 UTC, fromanywhere approved these changes

2019-11-10 14:36 UTC, merged